# -*- coding: utf-8 -*-
"""kernel_MexicanHat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WbMCvFQSFntkqqHKy9TEIFTgF2RxXNW1
"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from scipy import ndimage


'''
Is = Image.open('sudoku.png');
I = Is.convert('L');
I = np.asarray(I);
I = I / 255.0;
'''

def calc_ker(I, Is, K, sigma, verbose=False):
    #Matriz de ceros
    KR = np.zeros((K,K))

    mitad = K // 2

    for x in range(K):
        for y in range(K):
            X = x - mitad
            Y = y - mitad

            KR[x][y] = (1/(np.pi*sigma**4)) * ((1-(1/2))*((X**2+Y**2)/sigma**2)) * np.exp( - ((X**2+Y**2)/(2*sigma**2)))
    
    J1 = ndimage.convolve(I, KR, mode='constant', cval=0.0)
    plt.figure(figsize = (20,20))

    plt.subplot(3,3,1)
    plt.imshow(Is)
    plt.xlabel('Input Image')

    plt.subplot(3,3,2)
    plt.imshow(J1)
    plt.xlabel('Mexican Hat filter')
    return KR
